markdown: kramdown
url: ''
baseurl: null
title: Juan C. Perez Banuchi
description: From being a Assistant Store Manager  to a Full Stack Software Engineer
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Site, Template, Theme'
favicon-url: null
heroimage: >-
  https://scontent.fsig3-1.fna.fbcdn.net/v/t1.6435-9/125254165_10157714568321497_1640010521310453942_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=84a396&_nc_ohc=AIESiQjhaHQAX9ADFq4&_nc_ht=scontent.fsig3-1.fna&oh=b8b6872350a6131fd93d5e5ae6cf56a0&oe=60E31BEB
email: thedevslot@gmail.com
twitter_username: juancoprz
linkedin_username: juancprz
github_username: jcperezbanuchi
google-analytics: UA-163806439-1
author-name: TheDevsLot
author-image: >-
  https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-about: >-
  Hello, my name is Juan Carlos. I have a bachellor degree in Biological
  sciences, with sales experience in the pharmaceutical and retail industry.
author-url: 'https://github.com/jcperezbanuchi'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
