markdown: kramdown
url: ''
baseurl: null
title: Juan C. Perez Banuchi
description: Based in NYC. From being an Assistant Store Manager to a Full Stack Software Engineer.
site-image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHvjjNCkykXUjLlrnSAlzxpvKx8TlqfEaufqIDSIlzlgF8-Q4xb10NfAiUAIJqhJBWFTo&usqp=CAU'
site-keywords: 'Site, Template, Theme'
favicon-url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHAuDn0q8uP183fLrKFKvlpL6YZZaJZCv66g&usqp=CAU'
heroimage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHvjjNCkykXUjLlrnSAlzxpvKx8TlqfEaufqIDSIlzlgF8-Q4xb10NfAiUAIJqhJBWFTo&usqp=CAU'
email: juancarlosperez_23@yahoo.com
twitter_username: juancoprz
linkedin_username: juancprz
github_username: jcperezbanuchi
google-analytics: UA-163806439-1
author-name: Juan C Perez Banuchi
author-image: >-
  'https://scontent.fsig3-1.fna.fbcdn.net/v/t1.6435-9/53452790_10156166421016497_5813846093267468288_n.jpg?_nc_cat=111&ccb=1-3&_nc_sid=730e14&_nc_ohc=cUczD2y9vBQAX_Jf-w-&_nc_ht=scontent.fsig3-1.fna&oh=d1fccab6250d5c91cad740d4e62f50a0&oe=60E2D332'
author-about: >-
     Hello curious! I graduated from the University of Puerto Rico - Aguadilla campus with a bachellor degree in Biological sciences. 
     I'm a fast learner, animal lover, a traveler with a passion for technology. Since I moved to New York City (October, 2017), I've been searching and looking to learn programming, after a couple of years I started learning different languages on my own. 
     Today, I'm currently finishing a Software Engineer bootcamp at General Assembly, looking forward to learn more and more.
 
author-url: 'https://github.com/jcperezbanuchi'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: ''
compress_html:
  clippings: all
defaults:
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
